/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicProjectsRouteImport } from './routes/_public.projects'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicCompanyListRouteImport } from './routes/_public.company-list'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthOtpRouteImport } from './routes/_auth.otp'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as PublicServicesContractorRouteImport } from './routes/_public.services.contractor'
import { Route as PublicServicesConsultingRouteImport } from './routes/_public.services.consulting'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard.profile'
import { Route as DashboardTendersRouteImport } from './routes/_dashboard.tenders'
import { Route as DashboardProjectsRouteImport } from './routes/_dashboard.projects'
import { Route as DashboardCompaniesRouteImport } from './routes/_dashboard.companies'
import { Route as DashboardMessagesRouteImport } from './routes/_dashboard.messages'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProjectsRoute = PublicProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCompanyListRoute = PublicCompanyListRouteImport.update({
  id: '/company-list',
  path: '/company-list',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const PublicServicesContractorRoute = PublicServicesContractorRouteImport.update({
  id: '/services/contractor',
  path: '/services/contractor',
  getParentRoute: () => PublicRoute,
} as any)
const PublicServicesConsultingRoute = PublicServicesConsultingRouteImport.update({
  id: '/services/consulting',
  path: '/services/consulting',
  getParentRoute: () => PublicRoute,
} as any)

// Dashboard routes
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTendersRoute = DashboardTendersRouteImport.update({
  id: '/dashboard/tenders',
  path: '/dashboard/tenders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/dashboard/projects',
  path: '/dashboard/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCompaniesRoute = DashboardCompaniesRouteImport.update({
  id: '/dashboard/companies',
  path: '/dashboard/companies',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/dashboard/messages',
  path: '/dashboard/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof AuthLoginRoute
  '/otp': typeof AuthOtpRoute
  '/register': typeof AuthRegisterRoute
  '/about': typeof PublicAboutRoute
  '/company-list': typeof PublicCompanyListRoute
  '/contact': typeof PublicContactRoute
  '/projects': typeof PublicProjectsRoute
  '/services/consulting': typeof PublicServicesConsultingRoute
  '/services/contractor': typeof PublicServicesContractorRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/tenders': typeof DashboardTendersRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/companies': typeof DashboardCompaniesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof AuthLoginRoute
  '/otp': typeof AuthOtpRoute
  '/register': typeof AuthRegisterRoute
  '/about': typeof PublicAboutRoute
  '/company-list': typeof PublicCompanyListRoute
  '/contact': typeof PublicContactRoute
  '/projects': typeof PublicProjectsRoute
  '/services/consulting': typeof PublicServicesConsultingRoute
  '/services/contractor': typeof PublicServicesContractorRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/tenders': typeof DashboardTendersRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/companies': typeof DashboardCompaniesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/otp': typeof AuthOtpRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/company-list': typeof PublicCompanyListRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/projects': typeof PublicProjectsRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/services/consulting': typeof PublicServicesConsultingRoute
  '/_public/services/contractor': typeof PublicServicesContractorRoute
  '/_dashboard/dashboard': typeof DashboardIndexRoute
  '/_dashboard/dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/dashboard/tenders': typeof DashboardTendersRoute
  '/_dashboard/dashboard/projects': typeof DashboardProjectsRoute
  '/_dashboard/dashboard/companies': typeof DashboardCompaniesRoute
  '/_dashboard/dashboard/messages': typeof DashboardMessagesRoute
  '/_dashboard/dashboard/settings': typeof DashboardSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/otp'
    | '/register'
    | '/about'
    | '/company-list'
    | '/contact'
    | '/projects'
    | '/services/consulting'
    | '/services/contractor'
    | '/dashboard'
    | '/dashboard/profile'
    | '/dashboard/tenders'
    | '/dashboard/projects'
    | '/dashboard/companies'
    | '/dashboard/messages'
    | '/dashboard/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/otp'
    | '/register'
    | '/about'
    | '/company-list'
    | '/contact'
    | '/projects'
    | '/services/consulting'
    | '/services/contractor'
    | '/dashboard'
    | '/dashboard/profile'
    | '/dashboard/tenders'
    | '/dashboard/projects'
    | '/dashboard/companies'
    | '/dashboard/messages'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/_dashboard'
    | '/_auth/login'
    | '/_auth/otp'
    | '/_auth/register'
    | '/_public/about'
    | '/_public/company-list'
    | '/_public/contact'
    | '/_public/projects'
    | '/_public/'
    | '/_public/services/consulting'
    | '/_public/services/contractor'
    | '/_dashboard/dashboard'
    | '/_dashboard/dashboard/profile'
    | '/_dashboard/dashboard/tenders'
    | '/_dashboard/dashboard/projects'
    | '/_dashboard/dashboard/companies'
    | '/_dashboard/dashboard/messages'
    | '/_dashboard/dashboard/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/projects': {
      id: '/_public/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof PublicProjectsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/company-list': {
      id: '/_public/company-list'
      path: '/company-list'
      fullPath: '/company-list'
      preLoaderRoute: typeof PublicCompanyListRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/otp': {
      id: '/_auth/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/services/contractor': {
      id: '/_public/services/contractor'
      path: '/services/contractor'
      fullPath: '/services/contractor'
      preLoaderRoute: typeof PublicServicesContractorRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/services/consulting': {
      id: '/_public/services/consulting'
      path: '/services/consulting'
      fullPath: '/services/consulting'
      preLoaderRoute: typeof PublicServicesConsultingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/profile': {
      id: '/_dashboard/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/tenders': {
      id: '/_dashboard/dashboard/tenders'
      path: '/dashboard/tenders'
      fullPath: '/dashboard/tenders'
      preLoaderRoute: typeof DashboardTendersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/projects': {
      id: '/_dashboard/dashboard/projects'
      path: '/dashboard/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/companies': {
      id: '/_dashboard/dashboard/companies'
      path: '/dashboard/companies'
      fullPath: '/dashboard/companies'
      preLoaderRoute: typeof DashboardCompaniesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/messages': {
      id: '/_dashboard/dashboard/messages'
      path: '/dashboard/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/settings': {
      id: '/_dashboard/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}
const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicCompanyListRoute: typeof PublicCompanyListRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicProjectsRoute: typeof PublicProjectsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicServicesConsultingRoute: typeof PublicServicesConsultingRoute
  PublicServicesContractorRoute: typeof PublicServicesContractorRoute
}
const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicCompanyListRoute: PublicCompanyListRoute,
  PublicContactRoute: PublicContactRoute,
  PublicProjectsRoute: PublicProjectsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicServicesConsultingRoute: PublicServicesConsultingRoute,
  PublicServicesContractorRoute: PublicServicesContractorRoute,
}
const PublicRouteWithChildren = PublicRoute._addFileChildren(PublicRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardTendersRoute: typeof DashboardTendersRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardCompaniesRoute: typeof DashboardCompaniesRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
}
const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardTendersRoute: DashboardTendersRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardCompaniesRoute: DashboardCompaniesRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
}
const DashboardRouteWithChildren = DashboardRoute._addFileChildren(DashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
